### ISSUE TITLE
Lack of tag prevents installing

### ISSUE THREAD

**Issue by sebastianconcept** [vapor-community/postgresql-provider#1]
This is the feedback I've got from `swift build`

`Cloning https://github.com/qutheory/vapor-postgresql.git
error: No version tag found in (..Backend/Packages/vapor-postgresql) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"`

**Comment by tanner0101** [comment]
I will tag and release this with Vapor 0.15 and Fluent 0.8 in the coming days.

**Comment by sebastianconcept** [comment]
Awesome. Supporting pg will be great news @tannernelson !

**Comment by Kumuluzz** [comment]
@tannernelson, any updates on tagging this repo?

**Comment by tanner0101** [comment]
This is on a relatively old version of Swift and will take a bit of work to update. It will definitely be ready for Vapor 1.0 but for now the MySQL drivers are the best bet.

**Comment by Kumuluzz** [comment]
I'll start using MySQL for now then, but keep us posted if anything happens with the PostgreSQL provider :)

**Comment by a2** [comment]
@tannernelson Now that Vapor 1.0 is out, any chance that this will be tagged soon?

**Comment by anthonycastelli** [comment]
What is the holdup for not tagging this with a release?

**Comment by tanner0101** [comment]
@anthonycastelli we're waiting on #3

**Comment by natebird** [comment]
The provider has been tagged and released as [1.0](https://github.com/vapor/postgresql-provider/releases/tag/1.0.0)! Yay!
