### ISSUE TITLE
Package fails to build with postgresql-provider dependency

### ISSUE THREAD

**Issue by kamcma** [vapor-community/postgresql-provider#10]
When I add the postgresql-provider to my Package.swift, my build fails. Haven't even wired up anything in code, just added the dependency and try to build.

Here's my Package.swift:

```
let package = Package(
    name: "VaporDbTest",
	dependencies: [
            .Package(url: "https://github.com/vapor/vapor", majorVersion: 1),
            .Package(url: "https://github.com/vapor/postgresql-provider", majorVersion: 1)
	]
)
```

And here's the Terminal error I get:

```
Kyles-MacBook:VaporDbTest kylemcmahon$ swift build
warning: refname '1.0.0' is ambiguous.
warning: refname '1.0.0' is ambiguous.
HEAD is now at 3b56fda Merge pull request #3 from natebird/1.0
Resolved version: 1.0.0
warning: refname '1.1.12' is ambiguous.
warning: refname '1.1.12' is ambiguous.
HEAD is now at b39a3e3 Merge pull request #688 from vapor/skreutzberger-patch-1
Resolved version: 1.1.12
error: rename error: Directory not empty (66): /Users/kylemcmahon/Desktop/VaporDbTest/Packages/vapor.git -> /Users/kylemcmahon/Desktop/VaporDbTest/Packages/Vapor-1.1.12
```

If I comment out the postgresql-provider dependency, the package builds. Hoping this is a simple fix and I'm just doing something dumb. Thanks.

**Comment by kamcma** [comment]
Have determined this is not an issue specific to postgresql-provider; having this issue with the other providers as well. Closing the issue here.

**Comment by bernhardwaidacher** [comment]
Did you solve this problem? I have that too. Tested with postgresql and mysql

**Comment by kamcma** [comment]
You need to have the respective database installed on your machine. The provider packages depend on ... Idk exactly what, but they need to find some resources of the database installed in order to compile. I tried for some time to get it to find my Postgres.app instance, but couldn't figure that out so eventually gave up and installed PostgreSQL via Homebrew, which worked.

**Comment by bernhardwaidacher** [comment]
Oh thanks! Installed it with homebrew and everything works :)
