### ISSUE TITLE
ID must be int?

### ISSUE THREAD

**Issue by VolceOntra** [vapor-community/postgresql-provider#15]
I am unable to change the ID of a class to a string or UUID/GUID.  It seems to be forcing an integer...

**Comment by natebird** [comment]
Currently ID is an Int. We are looking at ways to make this more customizable but that requires a breaking API change and is tentatively slated for a 2.0 milestone.

**Comment by VolceOntra** [comment]
Thanks for the quick response

**Comment by tanner0101** [comment]
This is mentioned here: https://github.com/vapor/fluent/issues/125
