### ISSUE TITLE
Support Transactions 

### ISSUE THREAD

**Issue by diefer91** [vapor-community/postgresql-provider#17]
Currently, it's impossible to use transactions using the provider, even when doing raw queries. That's because everytime a query is executed, a new connection is created, making it impossible to perform transactions on the db.

**Comment by natebird** [comment]
This functionality is actively being worked on in Fluent and MySQL provider as well. I think we will be able to leverage this work once the PR has been approved in Fluent.

**Comment by natebird** [comment]
This was added on the postgresql library which the provider uses.

https://github.com/vapor-community/postgresql/pull/40/commits/2fe61def7025792f040c2d4944db8a316f658d3f
