### ISSUE TITLE
alpha / beta support?

### ISSUE THREAD

**Issue by treaves** [vapor-community/postgresql-provider#19]
I'm trying to test out 2.0alpha; I'm currently blocked with no 2.0.0 alpha release for postgresql-provider.  Any idea when it will be added?

Thanks.

**Comment by treaves** [comment]
Actually, I think the issue is with -driver, not -provider.

**Comment by 0xTim** [comment]
@treaves the issue will be with both given the Provider will need to point to Vapor 2 to work. I *think* that it shouldn't be much of an issue and none of the provider stuff has changed (currently) in Vapor 2

**Comment by natebird** [comment]
The first release with Vapor 2 beta support is here: https://github.com/vapor-community/postgresql-provider/releases/tag/2.0.0-beta.1

Please submit any bugs or regressions. A lot changed. :-)
