### ISSUE TITLE
Error raised at top level: VaporPostgreSQL.Provider.Error.noPostgreSQLConfig

### ISSUE THREAD

**Issue by victorgilalejandria** [vapor-community/postgresql-provider#21]
Hi, I've been dealing with this error the whole night. I even tried creating a new project and compiling again but nothing works. The provider doesn't seem to find the Config/secrets/postgresql.json file. Any idea what I can be missing. I'm attaching my Package.swift, main.swift and postgresql.json file just in case.
[Files.zip](https://github.com/vapor-community/postgresql-provider/files/963911/Files.zip)

**Comment by victorgilalejandria** [comment]
Any help with this?, Anyone?

**Comment by vzsg** [comment]
You should update your Vapor version to `minor: 5` in your Package.swift. Earlier versions – like 1.3.x in your case – have issues loading the configuration with Swift 3.1.
