### ISSUE TITLE
 Key hostname in Config/postgresql.json of type String required.  How to resolve it?

### ISSUE THREAD

**Issue by JsonRight** [vapor-community/postgresql-provider#29]
fatal error: Error raised at top level: Configuration error: Key hostname in Config/postgresql.json of type String required.

my code:
fluent.json:
"driver": "postgresql",

postgresql.json:
{
    "host": "127.0.0.1",
    "user": "username",
    "password": "password",
    "database": "postgres",
    "port": 8080
}

**Comment by JsonRight** [comment]
im new bird,thanks

**Comment by vzsg** [comment]
Change `host` to `hostname` in your postgresql.json.

**Comment by JsonRight** [comment]
oh，thanks，thanks，my eye is blind！！！
