### ISSUE TITLE
README: add PostgreSQLProvider to dependencies list

### ISSUE THREAD

**Issue by marc-medley** [vapor-community/postgresql-provider#33]
It would be helpful if README.md noted that `PostgreSQLProvider` needs to be added to target dependencies in `Package.swift`. For example: 

``` swift
.target(name: "App", dependencies: ["Vapor", "FluentProvider", "PostgreSQLProvider"]
```

… under the Swift 4 heading.

see StackOverflow new Vapor user question ["Add PostgreSQL to vapor project"](https://stackoverflow.com/questions/47117315/add-postgresql-to-vapor-project)

**Comment by natebird** [comment]
Go ahead and create a PR for this and we'll merge it in and you can get the credit. :-)
