### ISSUE TITLE
Setup multiple database access

### ISSUE THREAD

**Issue by crarau** [vapor-community/postgresql-provider#34]
My project has multiple PostgreSQL databases to connect to, located on different servers.  What's the way to achieve this?

**Comment by natebird** [comment]
Good question. I'm not sure it is possible right now. I haven't tried it. My guess would be to have multiple database providers (MySQL, PostgreSQL, MongoDB) and calling the different provider would establish the connection with that particular provider. They could be different PostgreSQL databases or different database types.

Try it out and see where it breaks, then report back. At this point, I'm not sure what the scope of the change would be to allow multiple database connections in the same app. It may require changes to the whole stack or maybe just the Provider repo.

**Comment by vzsg** [comment]
Many processes inside Fluent are geared towards a single, global database for your application. Case in point: `droplet.database`, `droplet.postgresql()` in this repo, or the fact that Entity classes have a single, static Database reference.

That doesn't mean however that you cannot connect to multiple databases. You can use the `PostgreSQLDriver.Driver.init(url: String)` initializer to create Driver instances manually, and use them as the `executor` parameter of any Fluent queries.

**Comment by crarau** [comment]
That’s a great idea. In the mean time I’ve used the raw queries to execute queries but using the fluent ones is much better. 

Chip
