### ISSUE TITLE
vapor update never ends, hangs on postgresql-driver

### ISSUE THREAD

**Issue by krummler** [vapor-community/postgresql-provider#38]
Hi there,

I'm following the steps in the readme, but updating never finishes, when I run using `--verbose`, it seems to hang on:

    Updating https://github.com/vapor-community/postgresql-driver.git

This never seems to complete. Am I missing something? 

This is my package.json:

	// swift-tools-version:4.0
	import PackageDescription

	let package = Package(
	    name: "Manager",
	    dependencies: [
	        // 💧 A server-side Swift web framework.
	        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
	        
	        // 🔵 Swift ORM (queries, models, relations, etc) built on SQLite 3.
	        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0"),
	        
	        // 👤 Authentication and Authorization layer for Fluent.
	        .package(url: "https://github.com/vapor/auth.git", from: "2.0.0"),
	        
	        // PostgreSQL support
	        .package(url: "https://github.com/vapor-community/postgresql-provider.git", .upToNextMajor(from: "2.1.0"))
	    ],
	    targets: [
	        .target(name: "App", dependencies: ["Authentication", "FluentSQLite", "Vapor", "FluentProvider", "PostgreSQLProvider"]),
	        .target(name: "Run", dependencies: ["App"]),
	        .testTarget(name: "AppTests", dependencies: ["App"])
	    ]
	)

**Comment by vzsg** [comment]
One fun fact about SPM dying on conflicting dependencies: the last line (which was in this case about `postgresql-driver`) has no significance. Fetching packages from git typically succeeds, but the version resolution stage gets stuck in an infinite loop - which confusingly doesn't print anything unless it's successful.

---

In your specific case, you're mixing Vapor 3 with a legacy, Vapor-2 only package: `vapor-community/postgresql-provider`. This causes the conflict and thus the infinite loop.

Remove that line, and fluent-sqlite too. The file should look like this:

```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "Manager",
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
        .package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0"),
        .package(url: "https://github.com/vapor/auth.git", from: "2.0.0"),
    ],
    targets: [
        .target(name: "App", dependencies: ["Authentication", "FluentPostgreSQL", "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

**Comment by krummler** [comment]
Thanks so much! I googled for vapor and postgreql and somehow ended up on old documentation: https://docs.vapor.codes/2.0/fluent/database/.
